export enum ProcessStateEnum {
    ApplicationCreated,
    PrimaryAdded,
    CoborrowerAdded,
    OfferInitiated,
    OfferPresented,
    TradePresented,
    TradeSelected,
    OfferGenerated,
    OfferSelected,
    OfferDeclined,
    OfferCustomized,
    CollateralAdded,
    FinanceSubmitted,
    ProcessFailed,
}

export enum VehicleTypeEnum {
    Auto = 'Auto',
    Motorcycle = 'Motorcycle'
}

export enum AutoTypeEnum {
    Used = 'USED',
    New = 'NEW'
}

export enum ApplicationTypeEnum {
    I = 'INDIVIDUAL',
    J = 'JOINT'
}

export enum ApplicationTypeDescriptionEnum {
    'INDIVIDUAL' = 'I',
    'JOINT' = 'J'
}

export enum AutoLoanPurpose {
    R = 'Auto Refinance',
    L = 'Lease Purchase',
    P = 'Company Car Purchase',
    C = 'Company Car Purchase Cash',
    LC = 'Lease Purchase Cash',
    AN = 'Auto New Purchase',
    AU = 'Auto Used Purchase',
    PC = 'Credit Card',
    HE = 'Home Equity',
    PP = 'Personal Loan'
}
export enum ApplicationStatusEnum {
    PRIMARY_APPLICANT_ADDED = 'PRIMARY_APPLICANT_ADDED',
    BUSINESS_ADDED = 'BUSINESS_ADDED',
    APPLICATION_SUBMITTED = 'APPLICATION_SUBMITTED',
    APPLICANT_SUBMITTED = 'APPLICANT_SUBMITTED',
    ALL_APPLICANTS_ADDED = 'ALL_APPLICANTS_ADDED',
    CASH_APPLICATION_SUBMITTED = 'CASH_APPLICATION_SUBMITTED',
    NO_OFFER_FOUND = 'NO_OFFER_FOUND',
    OFFER_GENERATION_INITIATED = 'OFFER_GENERATION_INITIATED',
    TRADELINE_SELECTED = 'TRADELINE_SELECTED',
    OFFER_GENERATED = 'OFFER_GENERATED',
    OFFER_GENERATED_WITH_LTV = 'OFFER_GENERATED_WITH_LTV',
    OFFER_DELIVERED = 'OFFER_DELIVERED',
    OFFER_VIEWED = 'OFFER_VIEWED',
    OFFER_SELECTED = 'OFFER_SELECTED',
    OFFER_ACCEPTED = 'OFFER_ACCEPTED',
    OFFER_CUSTOMIZED = 'OFFER_CUSTOMIZED',
    OFFER_DECLINED = 'OFFER_DECLINED',
    OFFER_EXPIRED = 'OFFER_EXPIRED',
    NO_BUREAU_REPORT = 'NO_BUREAU_REPORT',
    GENERATE_OFFER_NOT_INITIATED = 'GENERATE_OFFER_NOT_INITIATED',
    COLLATERAL_ADDED = 'COLLATERAL_ADDED',
    COLLATERAL_VALUE_RECEIVED = 'COLLATERAL_VALUE_RECEIVED',
    COLLATERAL_PROPERTY_UPDATE = 'COLLATERAL_PROPERTY_UPDATE',
    COLLATERAL_TRADELINE_ADDED = 'COLLATERAL_TRADELINE_ADDED',
    COLLATERAL_REQUEST_FAILED = 'COLLATERAL_REQUEST_FAILED',
    ADDITIONAL_INFO_ADDED = 'ADDITIONAL_INFO_ADDED',
    ADDITIONAL_DATA_ADDED = 'ADDITIONAL_DATA_ADDED',
    FINANCIAL_SUBMITTED = 'FINANCIAL_SUBMITTED',
    PROSPECT_APPLICATION = 'PROSPECT_APPLICATION',
    FINANCIAL_SUBMITTED_FAILED = 'FINANCIAL_SUBMITTED_FAILED',
    APPLICATION_FAILED = 'APPLICATION_FAILED',
    APPLICATION_WITHDRAWN = 'APPLICATION_WITHDRAWN',
    BUREAU_REPORT_RECEIVED = 'BUREAU_REPORT_RECEIVED'
}
